@BackendApis_HostAddress = https://localhost:7190
//@BackendApis_HostAddress = http://localhost:5045
@Token = c2ZMOBdfbWY4b1mY/ws6sEfAkhJLgXi3OE4rb2P1qP5wGCXMMFGOB2KZdcAIV8LoIjeWjOdLsHHl8Q6b8cJw5vTBDketjoKQER3/x4qnrcSzKb+7ElHpdY0U31r2j/KJSlUaXw4hCU45omzR1Myg0nqWToxslnqHSGpEb4Pb+Qhg/KCSTURz1JuvZCq/r+aSwu66in3uNCU62GjXljyCPNMhUTupri2spx/VIWF8loKMtWJDOyIau9lk7WAThIxqtKGDKcA7sXm6uY/aIcddSO6qY20Dbd/1d+H65cBEKm93axd3xB5lvNf/st7b2Nu0ow/xoxO8W3nnSS/TyPXIGQl071Wy+DHJgUVhK5xz6CgLOKYGQFzRvLmiuxiuS8O1H76GehdN58wjAkMKkZWmsml0yi6NPOeVHCVP/FS4HkkChxUVwZZM56DJqvE7QwRbs4xkPn9FMR5RgJXhgNzRtw+9/RBzPD5Z+HkLdyu4YjzcLfn9nQvz7guX1UUDHPa6xCsjGxiwDXQfcU+w71jlq88wreyOWRMrDGG5fVjRwqXM6UPoJmHq2kelAbj6ZtMM+IYXJKxdELRzmgtLDkkP3GaN+97gB5JFgJe4hpBIcDXZ/q5+OX/YK/D7iSlKRuMWB+S38bxe25LkHaiDvzE3vM5Zyza6onTG7APEKeK5SMnTiB0/MDvjBaTMwpGPxWNrOdeNy9H51qLo4Xa3UbbZv3sgAjyTj44iQ5RZKcUN7IRIFoo+zMxxBI5KgmnFY1cn

### Login User (POST)
POST {{BackendApis_HostAddress}}/api/v2/User/LoginUser
Content-Type: application/json
Accept: application/json
x-api-version: 2.0

{
  "cnic": "4210148778829",
  "password": "123456"
}

### Get Employees List (POST) with Paging
POST {{BackendApis_HostAddress}}/api/v2/Employees/IEnumerable-List
Authorization: Bearer {{Token}}
Content-Type: application/json
Accept: application/json
x-api-version: 2.0

{
  "pageSize": 10,
  "pageNumber": 1
}

###Fire JOB
POST {{BackendApis_HostAddress}}/api/v2/Jobs/fire-and-forget
Content-Type: application/json
Accept: application/json
x-api-version: 2.0
