@BackendApis_HostAddress = https://localhost:44311
@Token = c2ZMOBdfbWY4b1mY/ws6sEfAkhJLgXi3OE4rb2P1qP5wGCXMMFGOB2KZdcAIV8LoayOGruZcxX3k5ySarNVw6a/BDketjayyER3/+Y2wh8T/K4GsSUX+ZpAC5Ua9j9yjSlUaXxMnGWMgj0bR18KN1lOCZ5A3uUWODEBmc5LO9T55xp+JVn8qy5i4cHb5rs+dw8Hbij7oCyYkzHTMjCjzR5IbOiSohXWF7QDWHCVWu/bUmXFlPTJFt8VP1gYQl6JTsom6LYw8oX24uZ/7edJeX/W8WmkPbfHbMeLUhZlGLgRyaBRZwB8DoNXrjMaW2Mus6g/MqAuvdWbgWRXT09jhP1Zo7Hzo0QzSnWp9GtZdoxlRO5MKdWfB6eKJhjG3Z7LJApLgGBNMycsuLjYgkZKl7TBtxiHUE9mVXzVYhEmvHUkGhDs8nYEq9PnKqsN/RC5bs7VRb3tWCDgfh4Pmy8jjpx6/xBs2KRBK4VVSf3G5Xz+tOe7umCfykkm9i11fG4efiy8eD0CkP0EOdXGatkTEktEDspvERBQSVWHcDkrvwbXA7lzKDVvfh0acP7+5ZtB654wbGPc5C8BkjDZ8EXszmHOe8uLjLqV/2ZKPpqZPThnl6alLFFTTA5j44AJaU9ouM8S8sZpfz/ecAbDwwwF0s/dpsmWghkL7zS6TBvP1FMj/vGwAPDfKr3ERbW8Qp/IiJpCR56HeEw==

### Login User (POST)
POST {{BackendApis_HostAddress}}/api/v2/User/LoginUser
Content-Type: application/json
Accept: application/json
x-api-version: 2.0

{
  "cnic": "4210148778829",
  "password": "123456"
}

### Get Employees List (POST) with Paging
POST {{BackendApis_HostAddress}}/api/v2/Employees/Enumerable-List
Authorization: Bearer {{Token}}
Content-Type: application/json
Accept: application/json
x-api-version: 2.0

{
  "pageSize": 10,
  "pageNumber": 1
}
